dataset: csi800_direct
model:
  cycle: 3
training:
  learning_rate: 0.0005
  batch_size: 64
  eval_batch_size: 64
  max_epochs: 30
  patience: 5
  drop_last: true
  lr_schedule: type3
  num_workers: 2
